// Random album data that is added to Firestore
export const randomAlbumData = {
  albumNames: [
    "Midnight Echoes",
    "Neon Dreams",
    "Solar Symphony",
    "Electric Heart",
    "Cosmic Journey",
    "Urban Pulse",
    "Desert Wind",
    "Ocean Waves",
    "Mountain Song",
    "City Lights",
    "Digital Dawn",
    "Analog Memories",
    "Future Past",
    "Retro Revival",
    "Jazz Elements",
    "Classical Evolution",
    "Rock Revolution",
    "Hip Hop Nation",
    "Electronic Fusion",
    "Folk Tales",
    "Blues Highway",
    "Pop Paradise",
    "Soul Sessions",
    "Reggae Roots",
    "Metal Mayhem",
    "Indie Dreams",
    "Country Roads",
    "Latin Rhythms",
    "Gospel Glory",
    "World Beats"
  ],
  artists: [
    "The Soundscape",
    "Neon Knights",
    "Solar Collective",
    "Electric Dreams",
    "Cosmic Riders",
    "Urban Legends",
    "Desert Storm",
    "Ocean's Echo",
    "Mountain High",
    "City Sleepers",
    "Digital Dreamers",
    "Analog Kids",
    "Future Band",
    "Retro Rebels",
    "Jazz Fusion",
    "Classical Nova",
    "Rock Raiders",
    "Hip Hop Heroes",
    "Electronic Empire",
    "Folk Friends",
    "Blues Brothers",
    "Pop Stars",
    "Soul Sisters",
    "Reggae Rebels",
    "Metal Masters"
  ],
  genres: [
    "Rock",
    "Pop",
    "Hip Hop",
    "Jazz",
    "Classical",
    "Electronic",
    "Folk",
    "Blues",
    "Country",
    "Metal",
    "Indie",
    "R&B",
    "Soul",
    "Reggae",
    "World"
  ],
  albumReviews: [
    { text: "A masterpiece that transcends genres!", rating: 5 },
    { text: "Innovative sound design and incredible production!", rating: 5 },
    { text: "Every track is perfectly crafted.", rating: 5 },
    { text: "A groundbreaking album that sets new standards.", rating: 5 },
    { text: "Pure musical genius from start to finish!", rating: 5 },
    { text: "The harmonies are absolutely breathtaking.", rating: 5 },
    { text: "A perfect blend of artistry and technique.", rating: 5 },
    { text: "An unforgettable listening experience.", rating: 5 },
    { text: "Solid album with some great tracks.", rating: 4 },
    { text: "Good production value and memorable songs.", rating: 4 },
    { text: "Strong effort with minor flaws.", rating: 4 },
    { text: "Decent album but lacks consistency.", rating: 3 },
    { text: "Some good moments but nothing extraordinary.", rating: 3 },
    { text: "Average production, could be better.", rating: 3 },
    { text: "Disappointing follow-up to their previous work.", rating: 2 },
    { text: "Uninspired and formulaic.", rating: 2 },
    { text: "Poor production quality.", rating: 2 },
    { text: "Falls short of expectations.", rating: 2 },
    { text: "A complete misfire on all levels.", rating: 1 },
    { text: "Worst album I've heard this year.", rating: 1 },
    { text: "Save your money and skip this one.", rating: 1 },
    { text: "No redeeming qualities whatsoever.", rating: 1 }
  ]
};